#!/bin/bash
openssl genrsa -out cert/server-key.pem 1024
openssl req -new -key cert/server-key.pem -out cert/server-cert.tmp
openssl x509 -req -days 365 -in cert/server-cert.tmp -signkey cert/server-key.pem  -out cert/server-cert.pem
rm cert/server-cert.tmp
touch cert/cabundle.pem
